spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cpfjgdlds78s739e9eig-a:5432/schedule_changes
    username: anton
    password: Vs2WvUW6ibrkepcHJ9k9gZQk98ln0Hx3
  application:
    name: groupSchedule
  mvc:
    format:
      date: dd-MM-yyyy
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api
server:
  port: 8080
